; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
;projects[drupal][version] = "7.34"

; Modules
projects[views_bulk_operations][version] = "3.2"
projects[admin_menu][version] = "3.0-rc4"
projects[adminimal_admin_menu][version] = "1.5"
projects[append_file_info][version] = "1.x-dev"
projects[ctools][version] = "1.5"
projects[ckeditor][version] = "1.16"
projects[entity][version] = "1.5"
projects[fast_dblog][version] = "1.1"
projects[fences][version] = "1.0"
projects[field_collection][version] = "1.0-beta8"
projects[field_collection_fieldset][version] = "2.5"
projects[field_group][version] = "1.4"
projects[filefield_paths][version] = "1.0-beta4"
projects[globalredirect][version] = "1.5"
projects[google_analytics][version] = "2.0"
projects[httprl][version] = "1.14"
projects[jquery_update][version] = "2.4"
projects[l10n_update][version] = "1.1"
projects[lightbox2][version] = "1.0-beta1"
projects[menu_block][version] = "2.4"
projects[metatag][version] = "1.4"
projects[module_filter][version] = "2.0-alpha2"
projects[pathauto][version] = "1.2"
projects[redirect][version] = "1.0-rc1"
projects[token][version] = "1.5"
projects[transliteration][version] = "3.2"
projects[views][version] = "3.8"
projects[webform][version] = "4.2"
projects[xmlsitemap][version] = "2.1"
projects[yamaps][version] = "1.5"

projects[reactive_tools][type] = "module"
projects[reactive_tools][download][type] = "git"
projects[reactive_tools][download][url] = "git://github.com/reactivestudio/reactive_tools.git"

; Themes
;projects[maps_admin][version] = "1.4"
;projects[omega][version] = "4.3"
